public with sharing class ApplicationService {

    public void submitApplication(Id studentId, Id jobId) {

    }

    public void withdrawApplication(Id applicationId) {

    }

    public void approveApplication(Id applicationId) {

    }

    public void rejectApplication(Id applicationId) {

    }

    public void viewApplicationHistory(Id studentId) {

    }

    public void reopenApplication(Id applicationId) {

    }
}